language: c
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.2
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/install-debian.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/install-macos.sh; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/build-debian.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/build-macos.sh; fi
deploy:
  - provider: releases
    api_key:
      secure: AAAAB3NzaC1yc2EAAAABJQAAAQEAvW/uE1EInexJSrggUO2YeQNq+D5cUSVOHBHf3Jf7T77TxUHSUcHEtpcSoKAMU8N79CG5s1yFhwsi5VoKn5byiCPytttI4EX8Y+fe8Bp2rs4FNj2DAGzRPod/ZWtS5I3FmE9qUwejLz3Ft6PoHdkiFUCj6g1t9fEyV5NqGVvZ+pp51E5pFs9J5xfHB4Ew5172oJZQbuRad+D8UbJnAFh18xjYpHYA1IyYxfNsF+//MEHuYpZNeOssbrAY4+yktTDEi5a1cdrxWOBJQx/Ahn87FHcrBdMTYkznZJdG2bGOLkY+GRUDDYtTVH/6MUD+2kSRFkf5+MC3nALEh0h2p4Wquw==
    skip_cleanup: true
    file: build/solvespace.dmg
    on:
      repo: Evil-Spirit/solvespace-master
      tags: true
      condition: "$TRAVIS_OS_NAME == osx"
notifications:
  irc:
    channels:
      - "chat.freenode.net#solvespace"
    use_notice: true
    skip_join: true
